name: FlutterMedia
description: FlutterMedia

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_splash: ^0.0.2
  page_indicator: ^0.3.0
flutter:

  uses-material-design: true

  assets:
      - assets/icon/camera.png

